#!/usr/bin/env bash

cd $(dirname ${BASH_SOURCE[0]})

   git pull

if [[ -n $(git status -s) ]]; then
    echo "Changes found. Pushing changes..."
  git add -A && git commit -m 'Updated '$(date +%Y-%m-%d) && git push
else
    echo "No changes found. Skip pushing."
fi
